import chalk from "chalk";
import type { Command } from "commander";
import { withClient } from "../lib/sdk.ts";

/**
 * `lebop schema [-o file]` — dump Linear's GraphQL schema to stdout (or a
 * file). Pairs with `lebop raw` for offline schema-aware development:
 * dump once, point your editor at the SDL, write queries, then send via
 * `raw`.
 *
 * Uses GraphQL's standard introspection query — no special Linear endpoint.
 */
export function registerSchema(program: Command): void {
  program
    .command("schema")
    .description("dump Linear's GraphQL schema (SDL) to stdout or a file")
    .option("-o, --out <path>", "write to a file instead of stdout")
    .option("--json", "emit raw introspection JSON instead of SDL")
    .action(async (opts: { out?: string; json?: boolean }) => {
      const response = (await withClient((c) => c.client.rawRequest(INTROSPECTION_QUERY))) as {
        data: { __schema: unknown };
      };

      const output = opts.json
        ? JSON.stringify(response.data, null, 2)
        : sdlFromIntrospection(response.data);

      if (opts.out) {
        await Bun.write(opts.out, output.endsWith("\n") ? output : `${output}\n`);
        process.stderr.write(
          `${chalk.green("✓")} wrote ${output.length} bytes to ${chalk.cyan(opts.out)}\n`,
        );
      } else {
        process.stdout.write(output);
        if (!output.endsWith("\n")) process.stdout.write("\n");
      }
    });
}

const INTROSPECTION_QUERY = /* GraphQL */ `
  query IntrospectionQuery {
    __schema {
      queryType { name }
      mutationType { name }
      subscriptionType { name }
      types {
        ...FullType
      }
      directives {
        name
        description
        locations
        args {
          ...InputValue
        }
      }
    }
  }

  fragment FullType on __Type {
    kind
    name
    description
    fields(includeDeprecated: true) {
      name
      description
      args {
        ...InputValue
      }
      type {
        ...TypeRef
      }
      isDeprecated
      deprecationReason
    }
    inputFields {
      ...InputValue
    }
    interfaces {
      ...TypeRef
    }
    enumValues(includeDeprecated: true) {
      name
      description
      isDeprecated
      deprecationReason
    }
    possibleTypes {
      ...TypeRef
    }
  }

  fragment InputValue on __InputValue {
    name
    description
    type { ...TypeRef }
    defaultValue
  }

  fragment TypeRef on __Type {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
                ofType {
                  kind
                  name
                }
              }
            }
          }
        }
      }
    }
  }
`;

/**
 * Minimal SDL serializer for an introspection result. Renders types with
 * their fields + arg types + descriptions. Doesn't try to be a full
 * graphql-js compatible printer — just enough to be human-readable.
 */
function sdlFromIntrospection(data: unknown): string {
  const schema = (data as { __schema: { types: SchemaType[] } }).__schema;
  const lines: string[] = [];
  lines.push("# Linear GraphQL schema (SDL, abridged)");
  lines.push("# Generated by `lebop schema` via standard introspection.");
  lines.push("");

  for (const t of schema.types) {
    if (t.name.startsWith("__")) continue; // skip introspection meta-types
    if (t.description) {
      lines.push(`"""${escapeDescription(t.description)}"""`);
    }
    switch (t.kind) {
      case "OBJECT":
      case "INTERFACE": {
        const head = t.kind === "INTERFACE" ? "interface" : "type";
        const impl =
          t.interfaces && t.interfaces.length > 0
            ? ` implements ${t.interfaces.map((i) => i.name).join(" & ")}`
            : "";
        lines.push(`${head} ${t.name}${impl} {`);
        for (const f of t.fields ?? []) {
          if (f.description) lines.push(`  """${escapeDescription(f.description)}"""`);
          const args = (f.args ?? []).map((a) => `${a.name}: ${typeRef(a.type)}`).join(", ");
          const argSuffix = args ? `(${args})` : "";
          lines.push(`  ${f.name}${argSuffix}: ${typeRef(f.type)}`);
        }
        lines.push("}");
        break;
      }
      case "INPUT_OBJECT":
        lines.push(`input ${t.name} {`);
        for (const f of t.inputFields ?? []) {
          if (f.description) lines.push(`  """${escapeDescription(f.description)}"""`);
          lines.push(`  ${f.name}: ${typeRef(f.type)}`);
        }
        lines.push("}");
        break;
      case "ENUM":
        lines.push(`enum ${t.name} {`);
        for (const v of t.enumValues ?? []) {
          lines.push(`  ${v.name}`);
        }
        lines.push("}");
        break;
      case "SCALAR":
        lines.push(`scalar ${t.name}`);
        break;
      case "UNION":
        if (t.possibleTypes) {
          lines.push(`union ${t.name} = ${t.possibleTypes.map((p) => p.name).join(" | ")}`);
        }
        break;
    }
    lines.push("");
  }
  return lines.join("\n");
}

interface SchemaType {
  kind: string;
  name: string;
  description: string | null;
  fields?: { name: string; description: string | null; args: SchemaArg[]; type: SchemaTypeRef }[];
  inputFields?: { name: string; description: string | null; type: SchemaTypeRef }[];
  interfaces?: { name: string }[];
  enumValues?: { name: string; description: string | null }[];
  possibleTypes?: { name: string }[];
}
interface SchemaArg {
  name: string;
  description: string | null;
  type: SchemaTypeRef;
}
interface SchemaTypeRef {
  kind: string;
  name: string | null;
  ofType?: SchemaTypeRef | null;
}

function typeRef(t: SchemaTypeRef): string {
  if (t.kind === "NON_NULL") return `${typeRef(t.ofType as SchemaTypeRef)}!`;
  if (t.kind === "LIST") return `[${typeRef(t.ofType as SchemaTypeRef)}]`;
  return t.name ?? "Unknown";
}

function escapeDescription(d: string): string {
  return d.replace(/"""/g, '"\\"\\"');
}
